---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: keypair
    instance_type: t2.micro
    image: ami-965e6bf3
    region: us-east-2
  tasks:
    - name: Create key pair with key_material
      ec2_key:
        name: keypair
        region: us-east-2
        key_material: "{{lookup('file','/home/ubuntu/ansible/key/keypair.pub')}}" 
    - name: Launch Instance
      ec2: 
         key_name: "{{ keypair }}"
         group: default
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         aws_access_key: <ACCESSKEY>
         aws_secret_key: <SECRETKEY>
      register: ec2
